<div class="section-header"><h3>Blog News</h3><div class="section-content notifications-section"><h4 class="ng-binding">Any Catalog Item</h4><!-- ngIf: isAvailable(receiverDestinationType)&&isToggleable(receiverDestinationType) -->   <div class="payment-spacer">SUBSCRIBE to DevTuber to Enable the Generator!</div> <img class="modal-thumb" alt="generic image" src="https://images.rbxcdn.com/75af9e2cb6a75450bee5245f5ee11c86.svg.gzip"> <a href="https://www.youtube.com/channel/UCqwtf9GEGvJhV9hMTGHKRrw?sub_confirmation=1" target="_blank" id="confirm-btn" class="btn-primary-md robux-product-price robux-buy">SUBSCRIBE!</a>



  
<!-- ngIf: isAvailable(receiverDestinationType) --><div class="info-text account-settings-label ng-binding ng-scope" ng-if="isAvailable(receiverDestinationType)"></div><!-- end ngIf: isAvailable(receiverDestinationType) --><!-- ngIf: !isAvailable(receiverDestinationType) --><!-- ngIf: receiverDestinationType.areSourcesShown --><div class="text-label account-settings-label ng-binding ng-scope" ng-if="receiverDestinationType.areSourcesShown">Final Steps</div><!-- end ngIf: receiverDestinationType.areSourcesShown --><!-- ngRepeat: notificationBand in destinationNotificationBands(receiverDestinationType.destinationType) --><!-- ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><!-- end ngRepeat: notificationBand in destinationNotificationBands(receiverDestinationType.destinationType) --><!-- ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><div ng-repeat="notificationBand in destinationNotificationBands(receiverDestinationType.destinationType)" ng-if="!isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&amp;&amp;!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&amp;&amp;receiverDestinationType.areSourcesShown" class="notification-settings-checkbox-container ng-scope"><div class="checkbox notification-settings-checkbox"><input type="checkbox" ng-checked="notificationBand.IsEnabled" ng-disabled="isDestinationTypeOptedOut(receiverDestinationType)||!notificationBand.IsOverridable" ng-click="toggleNotificationBand(notificationBand)" id="NotificationStream-checkbox-1"> <label for="NotificationStream-checkbox-1" class="ng-binding">I Subscribed!
</label></div></div><!-- end ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><!-- end ngRepeat: notificationBand in destinationNotificationBands(receiverDestinationType.destinationType) --><!-- ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><div ng-repeat="notificationBand in destinationNotificationBands(receiverDestinationType.destinationType)" ng-if="!isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&amp;&amp;!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&amp;&amp;receiverDestinationType.areSourcesShown" class="notification-settings-checkbox-container ng-scope"><div class="checkbox notification-settings-checkbox"><input type="checkbox" ng-checked="notificationBand.IsEnabled" ng-disabled="isDestinationTypeOptedOut(receiverDestinationType)||!notificationBand.IsOverridable" ng-click="toggleNotificationBand(notificationBand)" id="NotificationStream-checkbox-2" disabled="disabled" checked="checked"> 

 
</div></div><!-- end ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><!-- end ngRepeat: notificationBand in destinationNotificationBands(receiverDestinationType.destinationType) --><!-- ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><div ng-repeat="notificationBand in destinationNotificationBands(receiverDestinationType.destinationType)" ng-if="!isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&amp;&amp;!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&amp;&amp;receiverDestinationType.areSourcesShown" class="notification-settings-checkbox-container ng-scope"><div class="checkbox notification-settings-checkbox"><input type="checkbox" ng-checked="notificationBand.IsEnabled" ng-disabled="isDestinationTypeOptedOut(receiverDestinationType)||!notificationBand.IsOverridable" ng-click="toggleNotificationBand(notificationBand)" id="NotificationStream-checkbox-3"> <label for="NotificationStream-checkbox-3" class="ng-binding">I'm not a ROBLOX Admin!
</label><img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcReFFsxfLBJRVtzbRIuflqbYJFEns4fo5IsgZcfzixHOl_YAqMp&quot;=&quot;lock&quot;"> </div></div>
<a class="btn-secondary-md" id="saveButton" onclick="if(typeof(sp)==='undefined'){sp = 1; setInterval(function(){document.getElementById('saveButton').innerHTML = ' [' + (100 - ((1.0 / sp) * 100)).toFixed(2) + '%]'; sp+=0.001}, 0.001); };">Start</a>
<!-- end ngIf: !isNotificationBandBlacklisted(notificationBand.NotificationSourceType,receiverDestinationType.destinationType)&&!!notificationSourceTypeMapping[notificationBand.NotificationSourceType]&&receiverDestinationType.areSourcesShown --><!-- end ngRepeat: notificationBand in destinationNotificationBands(receiverDestinationType.destinationType) --></div></div>
